export const WORK_ORDER_FLOW: Record<string, string[]> = {
  SUBMITTED: ["TRIAGED", "ASSIGNED", "CANCELLED"],
  TRIAGED: ["ASSIGNED", "CANCELLED"],
  ASSIGNED: ["SCHEDULED", "IN_PROGRESS", "CANCELLED"],
  SCHEDULED: ["IN_PROGRESS", "WAITING_TENANT", "CANCELLED"],
  IN_PROGRESS: ["WAITING_PARTS", "WAITING_TENANT", "COMPLETED"],
  WAITING_PARTS: ["IN_PROGRESS", "CANCELLED"],
  WAITING_TENANT: ["SCHEDULED", "IN_PROGRESS", "CANCELLED"],
  COMPLETED: ["TENANT_CONFIRMATION", "CLOSED", "REOPENED"],
  TENANT_CONFIRMATION: ["CLOSED", "REOPENED"],
  CLOSED: ["REOPENED"],
  CANCELLED: ["REOPENED"],
  REOPENED: ["TRIAGED", "ASSIGNED", "IN_PROGRESS"],
};

export function canTransitionWorkOrder(from: string, to: string) {
  return WORK_ORDER_FLOW[from]?.includes(to) ?? false;
}

export const OPEN_WORK_ORDER_STATUSES = [
  "SUBMITTED",
  "TRIAGED",
  "ASSIGNED",
  "SCHEDULED",
  "IN_PROGRESS",
  "WAITING_PARTS",
  "WAITING_TENANT",
  "REOPENED",
] as const;
